<template>
  <div class="app-breadcrumb">
    <VBreadcrumbs
      :items="breadcrumbItems"
      :divider="divider"
      :density="density"
      :color="color"
      class="pa-0"
    >
      <template #prepend>
        <VIcon
          v-if="showHomeIcon"
          icon="mdi-home"
          size="16"
          :color="color"
          class="mr-2"
        />
      </template>
      
      <template #item="{ item, index }">
        <VBreadcrumbsItem
          :disabled="item.disabled"
          :href="item.href"
          :to="item.to"
          :exact="item.exact"
          class="breadcrumb-item"
          :class="{
            'breadcrumb-item--active': index === breadcrumbItems.length - 1,
            'breadcrumb-item--clickable': !item.disabled && (item.to || item.href)
          }"
        >
          <VIcon
            v-if="(item as BreadcrumbItem).icon"
            :icon="(item as BreadcrumbItem).icon"
            size="16"
            class="mr-2"
          />
          {{ item.title }}
        </VBreadcrumbsItem>
      </template>
      
      <template #divider>
        <VIcon
          :icon="dividerIcon"
          size="14"
          :color="dividerColor"
          class="mx-2"
        />
      </template>
    </VBreadcrumbs>
    
    <!-- Actions (optional) -->
    <div v-if="actions.length > 0" class="app-breadcrumb__actions">
      <VBtn
        v-for="action in actions"
        :key="action.text"
        :color="action.color || 'primary'"
        :variant="action.variant || 'text'"
        :size="action.size || 'small'"
        :prepend-icon="action.icon"
        @click="action.handler"
      >
        {{ action.text }}
      </VBtn>
    </div>
  </div>
</template>

<script setup lang="ts">
interface BreadcrumbItem {
  title: string
  to?: string
  href?: string
  icon?: string
  disabled?: boolean
  exact?: boolean
}

interface BreadcrumbAction {
  text: string
  icon?: string
  handler: () => void
  color?: string
  variant?: 'flat' | 'outlined' | 'text'
  size?: 'small' | 'default' | 'large'
}

interface Props {
  items?: BreadcrumbItem[]
  divider?: string
  density?: 'default' | 'compact' | 'comfortable'
  color?: string
  showHomeIcon?: boolean
  actions?: BreadcrumbAction[]
  autoGenerate?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  items: () => [],
  divider: '/',
  density: 'default',
  color: 'primary',
  showHomeIcon: true,
  actions: () => [],
  autoGenerate: true
})

// Router and route
const router = useRouter()
const route = useRoute()

// Auth store for role-based breadcrumbs
const authStore = useAuthStore()

// Computed properties
const dividerIcon = computed(() => {
  switch (props.divider) {
    case '>':
      return 'mdi-chevron-right'
    case '→':
      return 'mdi-arrow-right'
    case '•':
      return 'mdi-circle-small'
    default:
      return 'mdi-chevron-right'
  }
})

const dividerColor = computed(() => {
  return 'neutral-400'
})

// Auto-generated breadcrumbs based on current route
const autoGeneratedItems = computed((): BreadcrumbItem[] => {
  if (!props.autoGenerate) return []
  
  const pathSegments = route.path.split('/').filter(segment => segment)
  const breadcrumbs: BreadcrumbItem[] = []
  
  // Always start with home/dashboard
  breadcrumbs.push({
    title: authStore.isAuthenticated ? 'Dashboard' : 'Home',
    to: authStore.isAuthenticated ? '/dashboard' : '/',
    icon: authStore.isAuthenticated ? 'mdi-view-dashboard' : 'mdi-home',
    exact: true
  })
  
  // Build breadcrumbs from path segments
  let currentPath = ''
  
  for (let i = 0; i < pathSegments.length; i++) {
    const segment = pathSegments[i]
    currentPath += `/${segment}`
    
    // Skip the last segment (current page) unless it's the only segment
    const isLast = i === pathSegments.length - 1
    
    const breadcrumbItem = getBreadcrumbForPath(currentPath, segment, isLast)
    if (breadcrumbItem) {
      breadcrumbs.push(breadcrumbItem)
    }
  }
  
  return breadcrumbs
})

const breadcrumbItems = computed(() => {
  return props.items.length > 0 ? props.items : autoGeneratedItems.value
})

// Helper function to generate breadcrumb items from path
const getBreadcrumbForPath = (path: string, segment: string, isLast: boolean): BreadcrumbItem | null => {
  // Define path mappings with icons and titles
  const pathMappings: Record<string, { title: string; icon?: string }> = {
    '/campaigns': { title: 'Campaigns', icon: 'mdi-castle' },
    '/campaigns/create': { title: 'Create Campaign', icon: 'mdi-plus' },
    '/campaigns/active': { title: 'Active Campaigns', icon: 'mdi-play-circle' },
    '/campaigns/archived': { title: 'Archived', icon: 'mdi-archive' },
    '/campaigns/templates': { title: 'Templates', icon: 'mdi-content-copy' },
    '/characters': { title: 'Characters', icon: 'mdi-account-group' },
    '/characters/create': { title: 'Create Character', icon: 'mdi-account-plus' },
    '/characters/active': { title: 'Active Characters', icon: 'mdi-account-check' },
    '/characters/retired': { title: 'Retired', icon: 'mdi-account-off' },
    '/ai-tools': { title: 'AI Tools', icon: 'mdi-brain' },
    '/ai-tools/npc-generator': { title: 'NPC Generator', icon: 'mdi-account-plus' },
    '/ai-tools/world-builder': { title: 'World Builder', icon: 'mdi-earth' },
    '/ai-tools/quest-generator': { title: 'Quest Generator', icon: 'mdi-map-marker-path' },
    '/library': { title: 'Content Library', icon: 'mdi-book-open-page-variant' },
    '/library/spells': { title: 'Spells', icon: 'mdi-auto-fix' },
    '/library/items': { title: 'Items', icon: 'mdi-sword' },
    '/library/monsters': { title: 'Monsters', icon: 'mdi-ghost' },
    '/sessions': { title: 'Game Sessions', icon: 'mdi-calendar-clock' },
    '/sessions/upcoming': { title: 'Upcoming', icon: 'mdi-calendar-plus' },
    '/sessions/history': { title: 'Session History', icon: 'mdi-history' },
    '/analytics': { title: 'Analytics', icon: 'mdi-chart-line' },
    '/profile': { title: 'Profile', icon: 'mdi-account' },
    '/settings': { title: 'Settings', icon: 'mdi-cog' },
    '/help': { title: 'Help & Support', icon: 'mdi-help-circle' },
    '/admin': { title: 'Admin Panel', icon: 'mdi-shield-account' }
  }
  
  // Check for exact path match
  if (pathMappings[path]) {
    return {
      title: pathMappings[path].title,
      icon: pathMappings[path].icon,
      to: isLast ? undefined : path,
      disabled: isLast
    }
  }
  
  // Handle dynamic segments (e.g., /campaigns/123)
  if (segment.match(/^[0-9a-f-]{36}$/i)) {
    // UUID - probably an ID
    return {
      title: 'Details',
      icon: 'mdi-information',
      disabled: true
    }
  }
  
  if (segment.match(/^\d+$/)) {
    // Numeric ID
    return {
      title: `#${segment}`,
      disabled: true
    }
  }
  
  // Fallback: capitalize segment
  const title = segment
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
  
  return {
    title,
    to: isLast ? undefined : path,
    disabled: isLast
  }
}

// Methods for programmatic breadcrumb updates
const updateBreadcrumbs = (items: BreadcrumbItem[]) => {
  // This could emit an event or update a store
  // For now, we'll just log it
  console.log('Breadcrumbs updated:', items)
}

const addBreadcrumb = (item: BreadcrumbItem) => {
  const newItems = [...breadcrumbItems.value, item]
  updateBreadcrumbs(newItems)
}

const removeBreadcrumb = (index: number) => {
  const newItems = breadcrumbItems.value.filter((_, i) => i !== index)
  updateBreadcrumbs(newItems)
}

// Expose methods for parent components
defineExpose({
  updateBreadcrumbs,
  addBreadcrumb,
  removeBreadcrumb
})
</script>

<style scoped>
.app-breadcrumb {
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 1rem;
}

.app-breadcrumb__actions {
  display: flex;
  gap: 0.5rem;
  align-items: center;
}

/* Breadcrumb item styling */
:deep(.breadcrumb-item--clickable) {
  cursor: pointer;
  transition: color 0.2s ease;
}

:deep(.breadcrumb-item--clickable:hover) {
  color: var(--v-theme-secondary);
}

:deep(.breadcrumb-item--active) {
  font-weight: 600;
  color: var(--v-theme-primary);
}

:deep(.breadcrumb-item--active .v-icon) {
  color: var(--v-theme-primary);
}

/* Custom breadcrumb styling */
:deep(.v-breadcrumbs-item) {
  display: flex;
  align-items: center;
}

:deep(.v-breadcrumbs-item--disabled) {
  opacity: 0.6;
  pointer-events: none;
}

/* Responsive adjustments */
@media (max-width: 600px) {
  .app-breadcrumb {
    flex-direction: column;
    align-items: flex-start;
    gap: 0.5rem;
  }
  
  :deep(.v-breadcrumbs) {
    font-size: 0.875rem;
  }
  
  :deep(.v-breadcrumbs .v-icon) {
    font-size: 14px;
  }
}

/* Compact density adjustments */
:deep(.v-breadcrumbs--density-compact) {
  padding: 0.25rem 0;
}

:deep(.v-breadcrumbs--density-compact .v-breadcrumbs-item) {
  font-size: 0.875rem;
}

:deep(.v-breadcrumbs--density-compact .v-icon) {
  font-size: 14px;
}
</style>
