// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/23/2025, 9:25:02 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/ethanstephens/Development/ai_dnd/web-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ethanstephens/Development/ai_dnd/web-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ethanstephens/Development/ai_dnd/web-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ethanstephens/Development/ai_dnd/web-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ethanstephens/Development/ai_dnd/web-app/plugins/**/*.{js,ts,mjs}","/Users/ethanstephens/Development/ai_dnd/web-app/composables/**/*.{js,ts,mjs}","/Users/ethanstephens/Development/ai_dnd/web-app/utils/**/*.{js,ts,mjs}","/Users/ethanstephens/Development/ai_dnd/web-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ethanstephens/Development/ai_dnd/web-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ethanstephens/Development/ai_dnd/web-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ethanstephens/Development/ai_dnd/web-app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;