-- PostgreSQL initialization script for D&D AI Campaign Manager
-- Development environment setup

-- Create additional databases if needed
-- CREATE DATABASE dndai_test;

-- Create extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Create schemas for different services (microservices approach)
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS campaigns;
CREATE SCHEMA IF NOT EXISTS characters;
CREATE SCHEMA IF NOT EXISTS ai_gateway;
CREATE SCHEMA IF NOT EXISTS notifications;
CREATE SCHEMA IF NOT EXISTS audit;

-- Grant permissions to developer user
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO developer;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA auth TO developer;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA campaigns TO developer;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA characters TO developer;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ai_gateway TO developer;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA notifications TO developer;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA audit TO developer;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO developer;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA auth TO developer;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA campaigns TO developer;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA characters TO developer;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ai_gateway TO developer;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA notifications TO developer;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA audit TO developer;

-- Set default privileges for future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO developer;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON TABLES TO developer;
ALTER DEFAULT PRIVILEGES IN SCHEMA campaigns GRANT ALL ON TABLES TO developer;
ALTER DEFAULT PRIVILEGES IN SCHEMA characters GRANT ALL ON TABLES TO developer;
ALTER DEFAULT PRIVILEGES IN SCHEMA ai_gateway GRANT ALL ON TABLES TO developer;
ALTER DEFAULT PRIVILEGES IN SCHEMA notifications GRANT ALL ON TABLES TO developer;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT ALL ON TABLES TO developer;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO developer;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON SEQUENCES TO developer;
ALTER DEFAULT PRIVILEGES IN SCHEMA campaigns GRANT ALL ON SEQUENCES TO developer;
ALTER DEFAULT PRIVILEGES IN SCHEMA characters GRANT ALL ON SEQUENCES TO developer;
ALTER DEFAULT PRIVILEGES IN SCHEMA ai_gateway GRANT ALL ON SEQUENCES TO developer;
ALTER DEFAULT PRIVILEGES IN SCHEMA notifications GRANT ALL ON SEQUENCES TO developer;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT ALL ON SEQUENCES TO developer;
